import { PromiseRecord } from '../types';

export const initialPromises: PromiseRecord[] = [
  {
    "id": "assam-2026-ucc",
    "sourceUrl": "https://newsonair.gov.in/assam-assembly-passes-ucc-bill-becoming-third-state-to-adopt-legislation/",
    "title": "Uniform Civil Code in Assam",
    "category": "Law and governance",
    "promiseText": "Move ahead with a Uniform Civil Code for Assam.",
    "status": "passed",
    "sourceTitle": "Assam assembly passes UCC Bill with ban on polygamy, live-in registration rules",
    "sourceDate": "2026-05-27",
    "sourceRef": "turn483419news1",
    "trackMetric": "Bill passed, rules notified, implementation started",
    "verificationRule": "Mark fulfilled only after notification / rules / implementation begin.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-2026-polygamy-ban",
    "sourceUrl": "https://timesofindia.indiatimes.com/india/assam-assembly-passes-ucc-bill-with-ban-on-polygamy-live-in-registration-rules/articleshow/131346393.cms",
    "title": "Ban polygamy",
    "category": "Law and governance",
    "promiseText": "Pass a law criminalising polygamy as part of the reform agenda.",
    "status": "passed",
    "sourceTitle": "'Historic step for women': Assam passes anti-polygamy bill",
    "sourceDate": "2025-11-27",
    "sourceRef": "turn483419news8",
    "trackMetric": "Bill passed and enforced",
    "verificationRule": "Mark fulfilled after the law is notified and enforced.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-2026-2lakh-jobs",
    "sourceUrl": "https://timesofindia.indiatimes.com/elections/assembly-elections/assam/photos/assam-polls-2026-from-ucc-to-employment-what-bjp-manifesto-sankalpa-patra-promises/photostory/129917422.cms",
    "title": "2 lakh jobs",
    "category": "Employment",
    "promiseText": "Create 2 lakh additional jobs through government recruitment and private sector growth.",
    "status": "announced",
    "sourceTitle": "Assam polls 2026: From UCC to employment - What BJP manifesto promises",
    "sourceDate": "2026-04-01",
    "sourceRef": "turn483419news5",
    "trackMetric": "Number of jobs announced vs actually created",
    "verificationRule": "Track separately for government posts, private jobs, and training-linked placements.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-2026-flood-18000cr",
    "sourceUrl": "https://timesofindia.indiatimes.com/elections/assembly-elections/assam/photos/assam-polls-2026-from-ucc-to-employment-what-bjp-manifesto-sankalpa-patra-promises/photostory/129917422.cms",
    "title": "₹18,000 crore flood control mission",
    "category": "Infrastructure",
    "promiseText": "Spend ₹18,000 crore in the first two years on flood control and river management.",
    "status": "announced",
    "sourceTitle": "Assam polls 2026: From UCC to employment - What BJP manifesto promises",
    "sourceDate": "2026-04-01",
    "sourceRef": "turn483419news5",
    "trackMetric": "Budget allocated, projects tendered, embankments completed",
    "verificationRule": "Mark in progress when budget allocation or tenders appear; fulfilled only when project milestones are completed.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-2026-infra-5lakhcr",
    "sourceUrl": "https://timesofindia.indiatimes.com/elections/assembly-elections/assam/photos/assam-polls-2026-from-ucc-to-employment-what-bjp-manifesto-sankalpa-patra-promises/photostory/129917422.cms",
    "title": "₹5 lakh crore infrastructure push",
    "category": "Infrastructure",
    "promiseText": "Invest ₹5 lakh crore in roads, rail, airports, river transport, and major connectivity projects.",
    "status": "announced",
    "sourceTitle": "Assam polls 2026: From UCC to employment - What BJP manifesto promises",
    "sourceDate": "2026-04-01",
    "sourceRef": "turn483419news5",
    "trackMetric": "Amount sanctioned and project execution status",
    "verificationRule": "Track official approvals, work orders, and completion stages.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-2026-health-50000cr",
    "sourceUrl": "https://timesofindia.indiatimes.com/elections/assembly-elections/assam/photos/assam-polls-2026-from-ucc-to-employment-what-bjp-manifesto-sankalpa-patra-promises/photostory/129917422.cms",
    "title": "₹50,000 crore healthcare expansion",
    "category": "Health",
    "promiseText": "Expand healthcare with a ₹50,000 crore investment plan.",
    "status": "announced",
    "sourceTitle": "Assam polls 2026: From UCC to employment - What BJP manifesto promises",
    "sourceDate": "2026-04-01",
    "sourceRef": "turn483419news5",
    "trackMetric": "Capital allocation, hospital upgrades, new facilities opened",
    "verificationRule": "Mark in progress after budget approval and execution orders.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-2026-economy-10lakhcr",
    "sourceUrl": "https://timesofindia.indiatimes.com/city/guwahati/will-work-to-make-state-10l-cr-economy-assam-cm/articleshow/131335127.cms",
    "title": "₹10 lakh-crore economy by 2028",
    "category": "Economy",
    "promiseText": "Transform Assam into a ₹10 lakh-crore economy by 2028.",
    "status": "target",
    "sourceTitle": "Will work to make state 10L-cr economy: Assam CM",
    "sourceDate": "2026-05-27",
    "sourceRef": "turn590610news2",
    "trackMetric": "State GSDP progress toward 2028 target",
    "verificationRule": "Track annually using GSDP and growth figures.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-2025-orunodoi-3",
    "sourceUrl": "https://www.bjp.org/pressreleases/assam-election-manifesto-2026",
    "title": "Orunodoi 3.0 expansion",
    "category": "Welfare",
    "promiseText": "Expand Orunodoi 3.0 with enhanced monthly support for beneficiaries.",
    "status": "launched",
    "sourceTitle": "Assam CM launches Orunodoi 3.0 with enhanced ₹1,250 monthly benefit",
    "sourceDate": "2025-10-07",
    "sourceRef": "turn590279news1",
    "trackMetric": "Monthly benefit amount and number of beneficiaries",
    "verificationRule": "Mark fulfilled when the updated benefit is actually disbursed to the target beneficiary base.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-2025-flight-3000",
    "sourceUrl": "https://www.bjp.org/pressreleases/assam-election-manifesto-2026",
    "title": "FLIGHT scheme for 3,000 youths",
    "category": "Employment",
    "promiseText": "Train 3,000 youths in Japanese language and link them to overseas jobs under the FLIGHT scheme.",
    "status": "in_progress",
    "sourceTitle": "3,000 to learn Japanese under FLIGHT scheme for overseas jobs",
    "sourceDate": "2025-07-23",
    "sourceRef": "turn483419news7",
    "trackMetric": "Number trained, placed, and retained in jobs",
    "verificationRule": "Track training intake separately from final placements.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-2025-investment-mous",
    "sourceUrl": "https://www.bjp.org/pressreleases/assam-election-manifesto-2026",
    "title": "Investment MoUs and job creation",
    "category": "Industry",
    "promiseText": "Convert investment commitments into operating projects and jobs across multiple sectors.",
    "status": "in_progress",
    "sourceTitle": "Assam govt signs MoUs for projects worth 22,900 crore",
    "sourceDate": "2025-05-25",
    "sourceRef": "turn127771news2",
    "trackMetric": "MoUs converted into functioning projects and jobs",
    "verificationRule": "Mark fulfilled only when investment moves from MoU to production or service delivery.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-2026-orunodoi-40lakh",
    "sourceUrl": "https://www.bjp.org/pressreleases/assam-election-manifesto-2026",
    "title": "Orunodoi disbursal to 40 lakh women",
    "category": "Welfare",
    "promiseText": "Continue large-scale direct benefit transfers to women beneficiaries under Orunodoi.",
    "status": "fulfilled",
    "sourceTitle": "Assam govt transfers Rs 9,000 each to 40 lakh women beneficiaries",
    "sourceDate": "2026-03-10",
    "sourceRef": "turn590279news2",
    "trackMetric": "Beneficiaries reached and amount transferred",
    "verificationRule": "Mark fulfilled when the DBT transfer is completed and documented.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-land-reclamation-5lakh-bigha",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Free 5 lakh bighas of encroached land",
    "category": "Law and governance",
    "promiseText": "Reclaim 5 lakh bighas of government land from encroachment during the new term.",
    "status": "announced",
    "trackMetric": "Total bighas reclaimed",
    "verificationRule": "Track district-wise eviction drives and official land records.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-welfare-expansion",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Expand welfare coverage",
    "category": "Welfare",
    "promiseText": "Strengthen and expand welfare schemes across Assam.",
    "status": "announced",
    "trackMetric": "Beneficiaries added and annual expenditure",
    "verificationRule": "Verify through budget allocations and beneficiary databases.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-free-education-kg-pg",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Free education from KG to PG for poor students",
    "category": "Education",
    "promiseText": "Provide free education from kindergarten to postgraduate level for economically weaker students.",
    "status": "announced",
    "trackMetric": "Students covered and institutions participating",
    "verificationRule": "Verify through education department notifications and beneficiary data.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-education-city",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Develop Assam Education City",
    "category": "Education",
    "promiseText": "Establish a major Education City in Assam for higher education and research.",
    "status": "announced",
    "trackMetric": "Land allocated, institutions established, project completion stages",
    "verificationRule": "Track DPR approvals, tenders, and construction progress.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-new-colleges-expansion",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Expand higher education infrastructure",
    "category": "Education",
    "promiseText": "Open new colleges and expand higher education facilities across Assam.",
    "status": "announced",
    "trackMetric": "Number of colleges and seats added",
    "verificationRule": "Verify through education department notifications and budget allocations.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-11000-farmer-support",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "₹11,000 annual farmer support",
    "category": "Agriculture",
    "promiseText": "Provide annual financial assistance of ₹11,000 to eligible farmers.",
    "status": "announced",
    "trackMetric": "Farmers receiving assistance and total disbursal",
    "verificationRule": "Track DBT records and agriculture department releases.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-agriculture-modernisation",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Modernise Assam agriculture",
    "category": "Agriculture",
    "promiseText": "Modernise agricultural infrastructure and improve productivity support systems.",
    "status": "announced",
    "trackMetric": "Mechanisation projects and subsidy distribution",
    "verificationRule": "Verify through departmental reports and subsidy schemes.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-10lakh-entrepreneurs",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Support 10 lakh entrepreneurs",
    "category": "Economy & Startup",
    "promiseText": "Support entrepreneurship and create opportunities for 10 lakh entrepreneurs.",
    "status": "announced",
    "trackMetric": "Registered startups and funded enterprises",
    "verificationRule": "Track startup registrations and government support programs.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-sez-development",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Develop Special Economic Zones",
    "category": "Industry",
    "promiseText": "Develop Special Economic Zones to attract manufacturing and investment.",
    "status": "announced",
    "trackMetric": "SEZ approvals and operational units",
    "verificationRule": "Verify through industrial policy notifications and project execution.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-electronics-manufacturing",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Expand electronics manufacturing",
    "category": "Industry",
    "promiseText": "Promote Assam as a hub for electronics manufacturing.",
    "status": "announced",
    "trackMetric": "Factories established and investment inflow",
    "verificationRule": "Track industrial MoUs and operational manufacturing units.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-eastern-gateway",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Develop Assam as Eastern Gateway of India",
    "category": "Economy",
    "promiseText": "Transform Assam into the economic gateway to Southeast Asia and Eastern India.",
    "status": "announced",
    "trackMetric": "Trade corridors and connectivity projects",
    "verificationRule": "Verify through infrastructure and trade policy execution.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-river-transport",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Expand river transport infrastructure",
    "category": "Infrastructure",
    "promiseText": "Develop modern river transport systems across Assam.",
    "status": "announced",
    "trackMetric": "Terminals, ferries, and routes operational",
    "verificationRule": "Track transport department implementation reports.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-new-airports",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Develop new airports",
    "category": "Infrastructure",
    "promiseText": "Expand aviation infrastructure through development of new airports.",
    "status": "announced",
    "trackMetric": "Airports approved and operational",
    "verificationRule": "Verify through AAI and Assam government announcements.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-vande-bharat-connectivity",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Expand Vande Bharat connectivity",
    "category": "Infrastructure",
    "promiseText": "Improve railway connectivity including Vande Bharat services.",
    "status": "announced",
    "trackMetric": "Routes launched and operational frequency",
    "verificationRule": "Track railway ministry and operational announcements.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-underwater-tunnel",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Construct Gohpur–Numaligarh underwater tunnel",
    "category": "Infrastructure",
    "promiseText": "Build the Gohpur–Numaligarh underwater tunnel project.",
    "status": "announced",
    "trackMetric": "Tender, construction progress, and completion",
    "verificationRule": "Track NHIDCL and infrastructure ministry updates.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-flood-free-mission",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Flood-free Assam mission",
    "category": "Disaster Management",
    "promiseText": "Launch long-term mission to reduce flood impact across Assam.",
    "status": "announced",
    "trackMetric": "Flood-prone area reduction and embankment work",
    "verificationRule": "Verify through water resources department progress reports.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-modern-flood-forecasting",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Modern flood forecasting systems",
    "category": "Disaster Management",
    "promiseText": "Install advanced flood forecasting and monitoring systems.",
    "status": "announced",
    "trackMetric": "Forecasting centers and real-time monitoring deployment",
    "verificationRule": "Track disaster management authority reports.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-drainage-modernisation",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Modernise drainage systems",
    "category": "Infrastructure",
    "promiseText": "Upgrade urban and rural drainage systems to reduce waterlogging.",
    "status": "announced",
    "trackMetric": "Drainage projects completed",
    "verificationRule": "Verify through municipal and PWD reports.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-proton-therapy-centre",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Establish proton therapy cancer facility",
    "category": "Health",
    "promiseText": "Develop advanced proton therapy treatment infrastructure in Assam.",
    "status": "announced",
    "trackMetric": "Facility approval and operational readiness",
    "verificationRule": "Track health department and hospital project reports.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-medical-hub-northeast",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Make Assam medical hub of Northeast",
    "category": "Health",
    "promiseText": "Develop Assam as a major healthcare hub for Northeast India.",
    "status": "announced",
    "trackMetric": "Medical tourism, hospitals, specialist services",
    "verificationRule": "Verify through healthcare infrastructure growth metrics.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-love-jihad-law",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Introduce Love Jihad law",
    "category": "Law and Governance",
    "promiseText": "Bring legal provisions against fraudulent religious conversion through marriage.",
    "status": "proposed",
    "trackMetric": "Bill introduction and legal status",
    "verificationRule": "Mark fulfilled only after legal enactment.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-anti-infiltration-law",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Strengthen anti-infiltration measures",
    "category": "Law and Governance",
    "promiseText": "Implement stricter anti-infiltration and border protection policies.",
    "status": "announced",
    "trackMetric": "Detection drives and policy implementation",
    "verificationRule": "Track legal measures and enforcement data.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-indigenous-land-protection",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Protect indigenous land rights",
    "category": "Indigenous Affairs",
    "promiseText": "Strengthen legal protection for indigenous land ownership.",
    "status": "announced",
    "trackMetric": "Protected land records and legal enforcement",
    "verificationRule": "Verify through land reform and tribal protection notifications.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-women-entrepreneurship",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Promote women entrepreneurship",
    "category": "Women & Welfare",
    "promiseText": "Increase support and financial opportunities for women entrepreneurs.",
    "status": "announced",
    "trackMetric": "Loans, startups, and beneficiaries",
    "verificationRule": "Track MSME and women welfare department records.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-startup-ecosystem",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Strengthen startup ecosystem",
    "category": "Economy & Startup",
    "promiseText": "Build a stronger startup ecosystem with funding and incubation support.",
    "status": "announced",
    "trackMetric": "Incubators created and startups funded",
    "verificationRule": "Verify through startup policy implementation reports.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-maritime-jobs",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Create maritime sector jobs",
    "category": "Employment",
    "promiseText": "Generate employment opportunities in the maritime and inland water transport sectors.",
    "status": "announced",
    "trackMetric": "Jobs created and training programs launched",
    "verificationRule": "Track employment department and transport ministry records.",
    "lastVerifiedAt": "2026-06-02"
  },
  {
    "id": "assam-aviation-sector-jobs",
    "sourceUrl": "https://www.bjp.org/files/inline-documents/Assam-Manifesto-2026-English.pdf",
    "title": "Create aviation sector employment",
    "category": "Employment",
    "promiseText": "Increase aviation-linked employment opportunities in Assam.",
    "status": "announced",
    "trackMetric": "Training programs and placements",
    "verificationRule": "Verify through aviation and skilling department reports.",
    "lastVerifiedAt": "2026-06-02"
  }
];
